### ISSUE TITLE
lower versions

### ISSUE THREAD

**Issue by zwkxgod** [Noryea/motionblur-fabric#13] opened 2024-04-15 13:43 UTC
can u do motion blur on lower versions like 1.16.5? Really a lot of people need on versions like 1.16.5/1.12.2/1.8.9

**Comment by slimakiswinka** [comment] 2024-04-15 13:54
Duplicate of #3 really

**Closed** 2024-04-23 09:48 UTC

**Comment by Noryea** [comment] 2024-04-26 08:44
For people looking for 1.8/1.12 version: There is already a motion blur mod for old version running on Forge, see [here](https://modrinth.com/mod/polyblur).
